extends: default

ignore: /**/testdata/  # ignore testdata files that are not relevant for linting

rules:
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1  # allow us to use space in brackets
  document-start:
    present: false
  indentation:
    spaces: 2
    indent-sequences: false  # make sure there is no indentation for sequences
  truthy:
    check-keys: false  # there is a problem with the "on" key in GitHub Actions
  quoted-strings:
    check-keys: true  # by default, only values are checked
    quote-type: single
    required: only-when-needed
  line-length:
    max: 92
