#!/usr/bin/env perl
# Copyright 2026 The go-yaml Project Contributors
# SPDX-License-Identifier: Apache-2.0

use strict;
use warnings;
use Cwd qw(abs_path getcwd);
use File::Copy qw(copy);
use File::Find qw(find);
use File::Path qw(make_path remove_tree);
use JSON::PP;

my $root = abs_path('.');
my $upstream = "$root/repos/yamlstar-plugin-json-comments";
my $local = $ENV{GO_YAML_JSON_COMMENTS_LOCAL} // '0';
my $module = 'github.com/yamlstar/yamlstar-plugin-json-comments';
my $query = $ENV{GO_YAML_JSON_COMMENTS_VERSION} || 'latest';
my $go = $ENV{GO_YAML_BUILD_GO} || 'go';

sub go_json {
    my ($directory, $workspace, @args) = @_;
    my $previous = getcwd();
    chdir $directory or die "Cannot enter $directory: $!\n";
    local $ENV{GOWORK} = $workspace;
    local $ENV{GOPROXY} = $ENV{GOPROXY} // 'direct';
    open my $result, '-|', $go, @args or die "Cannot run $go: $!\n";
    local $/;
    my $output = <$result>;
    close $result or die "Cannot run $go @args\n";
    chdir $previous or die "Cannot return to $previous: $!\n";
    return JSON::PP->new->decode($output);
}

$local =~ /\A[01]\z/ or die "JSON-COMMENTS-LOCAL must be 0 or 1\n";
$query =~ /\A(?:latest|v[0-9]+\.[0-9]+\.[0-9]+)\z/
    or die "Invalid JSON-comments version: $query\n";
if ($local eq '1') {
    -d "$upstream/parser" or die "Missing importable parser in $upstream\n";
    -f "$upstream/internal/glojure/pkg/yamlstar_plugin/json_comments/loader.go"
        or die "Missing generated parser sources in $upstream; run make generate there\n";
}
my $version = 'v0.0.0';
if ($local eq '1') {
    open my $manifest, '<', "$upstream/plugin.edn"
        or die "Cannot read $upstream/plugin.edn: $!\n";
    local $/;
    my $text = <$manifest>;
    close $manifest or die "Cannot close $upstream/plugin.edn: $!\n";
    $text =~ /:version\s+"([0-9]+\.[0-9]+\.[0-9]+)"/
        or die "Missing release version in $upstream/plugin.edn\n";
    $version = "v$1";
    $query eq 'latest' || $version eq $query
        or die "Requested local plugin $query has version $version\n";
}
else {
    my $info = go_json($root, 'off',
        'list', '-m', '-json', "$module\@$query");
    $version = $info->{Version} // '';
    $version =~ /\Av[0-9]+\.[0-9]+\.[0-9]+\z/
        or die "No tagged Go release for $module\@$query; " .
            "publish a v-prefixed release tag first\n";
    $query eq 'latest' || $version eq $query
        or die "Requested $module\@$query resolved to $version\n";
}
my $stage = "$root/.cache/cli-json-comments";
remove_tree($stage);
make_path($stage);

sub copy_tree {
    my ($from, $to) = @_;
    find({no_chdir => 1, wanted => sub {
        my $path = $File::Find::name;
        my $relative = substr($path, length($from));
        if (-d $path) { make_path("$to$relative"); }
        elsif (-f $path) { copy($path, "$to$relative") or die "$path: $!"; }
    }}, $from);
}

sub write_file {
    my ($path, $text) = @_;
    open my $file, '>', $path or die "$path: $!";
    print {$file} $text;
    close $file or die "$path: $!";
}

sub run_go {
    my ($directory, $workspace, @args) = @_;
    my $previous = getcwd();
    chdir $directory or die "Cannot enter $directory: $!\n";
    local $ENV{GOWORK} = $workspace;
    local $ENV{GOPROXY} = $ENV{GOPROXY} // 'direct';
    system {$go} $go, @args;
    my $status = $?;
    chdir $previous or die "Cannot return to $previous: $!\n";
    $status == 0 or die "Cannot run $go @args\n";
}

copy_tree("$root/cmd/go-yaml", $stage);
copy_tree("$root/plugin/json-comments/testdata", "$stage/testdata")
    if -d "$root/plugin/json-comments/testdata";
write_file("$stage/json_comments.go", <<"GO");
package main

import jsoncomments "go.yaml.in/yaml/v4/plugin/json-comments"

func init() {
	if err := jsoncomments.Register(); err != nil {
		panic(err)
	}
}
GO
run_go($stage, 'off', 'mod', 'init',
    'go.yaml.in/yaml/v4/json-comments-cli');
run_go($stage, 'off', 'mod', 'edit', '-go=1.24');
run_go($stage, 'off', 'mod', 'edit',
    "-replace=go.yaml.in/yaml/v4=$root");
run_go($stage, 'off', 'mod', 'edit',
    "-replace=go.yaml.in/yaml/v4/plugin/json-comments=" .
    "$root/plugin/json-comments");
run_go($stage, 'off', 'mod', 'edit', "-replace=$module=$upstream")
    if $local eq '1';
run_go($stage, 'off', 'get', 'go.yaml.in/yaml/v4');
run_go($stage, 'off', 'get',
    'go.yaml.in/yaml/v4/plugin/json-comments');
run_go($stage, 'off', 'get', "$module\@$version");
run_go($stage, 'off', 'mod', 'tidy');
my $selected_info = go_json($stage, 'off',
    'list', '-m', '-json', $module);
my $selected = $selected_info->{Version} // '';
$selected eq $version
    or die "Requested $module\@$version but selected $selected\n";

my $workdir = "$root/.cache/json-comments-work";
remove_tree($workdir);
make_path($workdir);
run_go($workdir, 'off', 'work', 'init',
    $root, "$root/plugin/json-comments", $stage);
my $workfile = "$workdir/go.work";
run_go($workdir, $workfile, 'work', 'edit', '-go=1.24');
run_go($workdir, $workfile, 'work', 'edit',
    "-replace=$module=$upstream") if $local eq '1';
