name: Go

on:
  push:
    branches: [ main, v3, v2, v1 ]
  pull_request:
    branches: [ main, v3, v2, v1 ]

permissions: read-all

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
      with:
        persist-credentials: false
    - name: Run linter
      run: make lint

  go-versions:
    name: Lookup Go versions
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.latest-patches.outputs.matrix }}
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
    # yamllint disable-line rule:line-length
    - uses: arnested/go-version-action@978371bd4d8cad0f54106c8be4273e2fcdd74f57  # v1.1.23
      id: versions
    - name: Get latest patch for each minor version
      id: latest-patches
      run: .github/workflows/bin/get-versions
           '${{ steps.versions.outputs.matrix }}'

  build:
    runs-on: ubuntu-latest
    needs: go-versions
    continue-on-error: true  # make sure to run all versions, even if one fails
    strategy:
      matrix:
        go-version: ${{ fromJSON(needs.go-versions.outputs.matrix) }}
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
      with:
        persist-credentials: false
    - name: Run yaml-test-suite tests
      run: make test-yts GO-VERSION=${{ matrix.go-version }}
    - name: Run unit tests
      run: make test v=1 GO-VERSION=${{ matrix.go-version }}
